
name = "Market"
license = "MIT"
licenselink = "https://github.com/anc02d/hugo-market-theme"
description = "a product display catalog"
homepage = "http://noeldevelops.com/"
tags = ["company", "bootstrap", "responsive", "custom themes", "product"]
features = []
min_version = "0.21"


[author]
  name = "Noel Cothren"
  homepage = "http://noeldevelops.com"
